### ISSUE TITLE
python should be python2

### ISSUE THREAD

**Issue by fommil** [elhigu/opencl-testsuite#5]
If I run `make check` on archlinux, which uses python3 by default, I get

```
AttributeError: '_Environ' object has no attribute 'has_key'
make[1]: *** [CMakeFiles/check.dir/build.make:57: CMakeFiles/check] Error 1
```

this is remedied by manually changing this line of the `build.make` to use `python2` instead of `python` (I don't know cmake to fix this properly), or updating the underlying files to python3 :smile:

**Comment by elhigu** [comment]
best solution would be to make python code compatible with python3 :) I haven't been working with OpenCL for a long time so I haven't had any motivation to keep this suite updated. Would be nice if someone else would take ownership of this project.
